S7_sorting
valntyn/products-e-commerce pull request #9
Opened 2023-05-17 07:48 UTC by valntyn

[DEMO](https://valntyn.github.io/products-e-commerce/#/products)

2023-05-17 16:01 UTC, Yuliia143 requested changes

2023-05-17 16:01 UTC, Yuliia143 commented on src/components/Sort/SortLink/index.tsx
> +  const isReversed = searchParams.get('order') === 'desc';
Enum ?

2023-05-17 16:01 UTC, Yuliia143 commented on src/components/Sort/SortLink/index.tsx
> +  const dispatch = useAppDispatch();
It's better to declare useAppDispatch before search params

2023-05-17 16:01 UTC, Yuliia143 commented on src/components/Sort/SortLink/index.tsx
> +    if (!isReversed) {
Why first 'if' use just condition , but second/third - variables?

2023-05-17 16:01 UTC, Yuliia143 commented on src/components/Sort/SortLink/index.tsx
> +    return undefined;
?

2023-05-17 16:01 UTC, Yuliia143 commented on src/components/Sort/index.tsx
> +    const sortInParams = searchParams.get('sort') || null;
Why || null ? Won't undefined be false for the condition below ?

2023-05-17 16:01 UTC, Yuliia143 commented on src/store/selectors/selectFilteredProducts.ts
> +          && (fixedPrice < selectedPrice[0] || fixedPrice > selectedPrice[1])
It's better to create variables for conditions to have better understanding what they mean

2023-05-18 05:46 UTC, valntyn commented on src/components/Sort/SortLink/index.tsx
> +  const dispatch = useAppDispatch();
I'll remember, fixed it.

2023-05-18 05:47 UTC, valntyn commented on src/components/Sort/SortLink/index.tsx
> +    if (!isReversed) {
I changed the structure of the function, now it looks better. I'll remember to take out logic in variables.

2023-05-18 05:47 UTC, valntyn commented on src/components/Sort/index.tsx
> +    const sortInParams = searchParams.get('sort') || null;
fixed it

2023-05-18 05:48 UTC, valntyn commented on src/store/selectors/selectFilteredProducts.ts
> +          && (fixedPrice < selectedPrice[0] || fixedPrice > selectedPrice[1])
I'll remember, made it better.

2023-05-18 05:48 UTC, valntyn commented on src/components/Sort/SortLink/index.tsx
> +  const isReversed = searchParams.get('order') === 'desc';
changed type for sort in props to enum

2023-05-18 05:50 UTC, valntyn commented on src/components/Sort/SortLink/index.tsx
> +    return undefined;
I have my linter configured in a way that doesn't allow me to create a function that doesn't return anything. I improved this function and will remember.

2023-05-19 05:47 UTC, Yuliia143 approved these changes

2023-05-19 05:48 UTC, merged